//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CroBooks.Web.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResource {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResource() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("CroBooks.Web.Resources.AppResource", typeof(AppResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string Calendar_Title {
            get {
                return ResourceManager.GetString("Calendar_Title", resourceCulture);
            }
        }
        
        public static string Home_Title {
            get {
                return ResourceManager.GetString("Home_Title", resourceCulture);
            }
        }
        
        public static string Loading_Loading {
            get {
                return ResourceManager.GetString("Loading_Loading", resourceCulture);
            }
        }
        
        public static string Menu_Callendar {
            get {
                return ResourceManager.GetString("Menu_Callendar", resourceCulture);
            }
        }
        
        public static string Menu_Home {
            get {
                return ResourceManager.GetString("Menu_Home", resourceCulture);
            }
        }
        
        public static string Menu_MyCompany {
            get {
                return ResourceManager.GetString("Menu_MyCompany", resourceCulture);
            }
        }
        
        public static string MyCompany_Title {
            get {
                return ResourceManager.GetString("MyCompany_Title", resourceCulture);
            }
        }
        
        public static string Setup_CreateAdmin {
            get {
                return ResourceManager.GetString("Setup_CreateAdmin", resourceCulture);
            }
        }
        
        public static string Setup_CreateCompany {
            get {
                return ResourceManager.GetString("Setup_CreateCompany", resourceCulture);
            }
        }
        
        public static string Setup_Setup {
            get {
                return ResourceManager.GetString("Setup_Setup", resourceCulture);
            }
        }
        
        public static string Clients_Title {
            get {
                return ResourceManager.GetString("Clients_Title", resourceCulture);
            }
        }
        
        public static string Menu_Clients {
            get {
                return ResourceManager.GetString("Menu_Clients", resourceCulture);
            }
        }
        
        public static string Client {
            get {
                return ResourceManager.GetString("Client", resourceCulture);
            }
        }
    }
}
